version: '3'

services:
  mgw-secret-manager:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
      target: prod
    container_name: mgw-secret-manager2
    image: mgw-secret-manager
    ports:
      - 8080:8080
    environment:
      - TMPFS_PATH=/tmp
      - ENABLE_ENCRYPTION=false
      - DB_FILE_PATH=/tmp/db.sqlite
      - MASTER_KEY_FILE_PATH=/tmp/key
    volumes:
      - /tmp:/tmp

# eShVmYq3t6w9z$C&E)H@McQfTjWnZr4u example 32 byte encryption key