version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10

  mgw-secret-manager:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
      target: prod
    container_name: mgw-secret-manager2
    image: mgw-secret-manager
    ports:
      - 8080:8080
    environment:
      - TMPFS_PATH=/tmp
      - ENABLE_ENCRYPTION=false
      - DB_CONNECTION_URL=user:password@tcp(db:3306)/db
      - MASTER_KEY_FILE_PATH=/tmp/key
      - LOGGER_TERMINAL=true
      - DEV=true
    volumes:
      - /tmp:/tmp
    depends_on:
      db:
        condition: service_healthy

# eShVmYq3t6w9z$C&E)H@McQfTjWnZr4u example 32 byte encryption key